name: Start parser
on: push
env:
  TOKEN: ${{ secrets.TOKEN }}
  ADMIN_ID: ${{ secrets.ADMIN_ID }}
  FLAT_URL: ${{ secrets.FLAT_URL }}
jobs:
 build-node:
  runs-on: ubuntu-latest
  steps:
   - name: Get repository code
     uses: actions/checkout@v3
   - name: Install dependencies
     run: npm ci
   - name: Run parser
     run: node app.js "TOKEN=${{ secrets.TOKEN }} ADMIN_ID=${{ secrets.ADMIN_ID }} FLAT_URL=${{ secrets.FLAT_URL }}"
     env:
       CI: true






